gh-38: Create a Data Model level Profile to identify core data specif…
MauroDataMapper-Plugins/mdm-plugin-explorer pull request #39
Opened 2024-03-05 14:45 UTC by NigelPalmer

…ication table

To build this you will need to build the mdm-plugin-explorer and then publish it to maven local. Then in the mdm-core make sure that the local copy is reference in build.gradle.
```
grails {
    plugins {
        ...
        runtimeOnly 'uk.ac.ox.softeng.maurodatamapper.plugins:mdm-plugin-explorer:1.0.0-SNAPSHOT'
    }
}
```

To test this you will need to login to the standard Mauro UI. Then select a data model and add the new "Mauro Data Explorer - Query Builder Core Table" to that profile. The validate button will tell you if the data you have entered is correct.
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/110250803/4371e8ae-9bd9-4269-9779-66fb56539e70)

This new profile has been created to identify the core of a star schema. The MDE expects the data model to be a star schema and the query builder will be using the information from this new profile to identify which table is the core.

Here is a simple data model that can be imported into your copy of Mauro to test this work. The core table is the Patient table.
[patientdb_20240305T143738.json](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/files/14496810/patientdb_20240305T143738.json)

2024-03-06 13:37 UTC, greg-at-occ requested changes
A couple of minor suggestions for you to look at. I didn't get the thing working but I didn't feel like it was worth the cost-benefit to do so at this stage. Let me know if you disagree

2024-03-06 13:37 UTC, greg-at-occ commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderCoreTableProfileProviderService.groovy
> +                    errors.rejectValue("fields[0].currentValue", 'datamodel.not.found',
Would it be better to handle this by throwing an Exception, if it should never happen? I assume this validation is intended to be shown to the end user and they can't really act on this message

2024-03-06 13:37 UTC, greg-at-occ commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderFunctionalSpec.groovy
> +        when:
To make it a bit clearer what is going on, I think it would be nice to have:
137   given: "The user has complete the profile with the given value for the coreTable field"
154   when: "The profile is validated"
160: then: "The expected validation results are produced (expectedErrors)"

2024-03-06 13:37 UTC, greg-at-occ commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderFunctionalSpec.groovy
> +    def setup() {
It would be nice to have a comment explaining what the setup does (I think it's another "given" for the test, but you only want it to happen once for performance reasons, correct?)

2024-03-11 09:09 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderCoreTableProfileProviderService.groovy
> +                    errors.rejectValue("fields[0].currentValue", 'datamodel.not.found',
Updated as suggested

2024-03-11 09:16 UTC, NigelPalmer commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderFunctionalSpec.groovy
> +        when:
Updated as suggested

2024-03-11 09:20 UTC, NigelPalmer commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/querybuilder/QueryBuilderFunctionalSpec.groovy
> +    def setup() {
Updated as suggested

2024-03-11 09:32 UTC, greg-at-occ approved these changes
Clearer now, thanks!

2024-03-11 09:44 UTC, merged