Feature/gh 36 sql exporter
MauroDataMapper-Plugins/mdm-plugin-explorer pull request #41
Opened 2024-03-28 18:39 UTC by NigelPalmer

2024-04-01 10:08 UTC, abwilson23 commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataSchema = dataModel.dataClasses.find((dataClass) -> {dataClass.label == entityParts[0]})
Doesn't appear to be needed.
```suggestion
```

2024-04-01 10:08 UTC, abwilson23 commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataTable = dataSchema.dataClasses.find((dataClass) -> {dataClass.label == entityParts[1]})
As above
```suggestion
```

2024-04-01 10:09 UTC, abwilson23 commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataElement = dataTable.dataElements.find((dataElement) -> {dataElement.label == json.field as String})
As above 
```suggestion
```

2024-04-01 11:44 UTC, abwilson23 commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/SqlExportTableBuilderService.groovy
> +    /**
I don't think it's necessary to refactor, but I just want to note that I find it a bit difficult to keep track of what's going on in this class because of the decision to mutate (a non class property) by reference in these private methods rather than having them be strongly typed. That being said, these dataModels can be pretty large so I think there's a good argument for in place mutation vs a pure function approach.

2024-04-01 11:54 UTC, abwilson23 commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/DataModelReaderService.groovy
> +        def referenceSchema = dataModel.childDataClasses.find {it.label == schemaName.trim()}
I just want to confirm that neither `dataModel.childDataClasses` here or `dataClass.dataElements` below allow for the possibility of duplicate labels. If they do, this find will only return the first match.

2024-04-01 15:47 UTC, abwilson23 commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/reader/MeqlReaderServiceSpec.groovy
> +        /*
Can these be removed? Or will they be added in later?

2024-04-01 17:09 UTC, abwilson23 commented
**Functional testing**

1. Attempting to export a data specification from my Nautilus DB that appears well-formed in the mdm-explorer (has no obvious error messages) produces the following unhelpful error message. 

```json
{
  "headers": {
    "normalizedNames": {},
    "lazyUpdate": null
  },
  "status": 500,
  "statusText": "OK",
  "url": "http://localhost:8080/api/dataModels/108f3b67-1358-469e-81d4-09d9f4343852/export/uk.ac.ox.softeng.maurodatamapper.plugins.explorer.provider.exporter/DataModelSqlExporterService/1.0",
  "ok": false,
  "name": "HttpErrorResponse",
  "message": "Http failure response for http://localhost:8080/api/dataModels/108f3b67-1358-469e-81d4-09d9f4343852/export/uk.ac.ox.softeng.maurodatamapper.plugins.explorer.provider.exporter/DataModelSqlExporterService/1.0: 500 OK",
  "error": {}
}
```

Here are the cohort/data queries of the data specification I attempted to export:
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/6440992/355f142d-061d-41ed-b5da-bf65efd8b82c)

2. Possible issue with the AND / OR parsing. I attempted to export the following:
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/6440992/42337cdf-f204-4ddf-9f4f-047d0cf6110f)

which was successful and created this sql:
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/6440992/471687d9-7c5b-452a-8a02-48d400cef6c9)

However, it seems like the first OR should be an AND, no? I tested swapping the outer AND to be an OR as follows:
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/6440992/0cba6acb-1fe0-4323-afd6-d0d1a174f653)

which was successful and outputted this sql which appears correct to me.
![image](https://github.com/MauroDataMapper-Plugins/mdm-plugin-explorer/assets/6440992/a23f7137-701e-47a6-aec8-6e88f36c6d69)

2024-04-01 17:21 UTC, abwilson23 requested changes, later dismissed
Overall looks and seems to work well. There are some functional issues around error handling and possible minor issues during query -> sql conversion around AND/OR operators. Addtionally I've left some minor comments that I'll leave up to you to address or not.

2024-04-02 07:58 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataSchema = dataModel.dataClasses.find((dataClass) -> {dataClass.label == entityParts[0]})
Removed

2024-04-02 07:58 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataTable = dataSchema.dataClasses.find((dataClass) -> {dataClass.label == entityParts[1]})
Removed

2024-04-02 07:58 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/MeqlReaderService.groovy
> +        // def dataElement = dataTable.dataElements.find((dataElement) -> {dataElement.label == json.field as String})
Removed

2024-04-02 08:03 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/SqlExportTableBuilderService.groovy
> +    /**
Having re-engineered this solution several times, I am not doing so again. These changes would require more thought. Removing mutation also removes some shared functions and by moving everything to the upper level can result in a bloated function that the reviewer would then ask to be broken down. I think the code as it stands has a clear separation between data extraction and manipulation, and writing that data to the data objects. I'm sure this could be done better, but I do not think spending another couple of days refactoring this gains us enough benefit for the time cost.

2024-04-02 08:04 UTC, NigelPalmer commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/reader/MeqlReaderServiceSpec.groovy
> +        /*
To be added...

2024-04-08 13:22 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/reader/DataModelReaderService.groovy
> +        def referenceSchema = dataModel.childDataClasses.find {it.label == schemaName.trim()}
If `dataModel.childDataClasses` had duplicates that would mean there were two schemas in the database with the same name. That is not possible. Likewise if there were duplicate `dataElements` with the same name in a `dataClass`, that would mean a sql table had two different columns with the same name. Again, not possible. So no changes are required.

2024-04-12 17:12 UTC, NigelPalmer commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/reader/MeqlReaderServiceSpec.groovy
> +        /*
More tests have been added. All services now have tests.

2024-04-12 17:17 UTC, NigelPalmer commented
Null dates are now exported in the SQL.
AND and OR issue is now fixed.
A lot more tests have been added.

2024-04-16 14:19 UTC, OButlerOcc reviewed
Some minor feedback. The tests work and test have good coverage with a variety of scenarios, I like the explained steps and new givens format, it makes them much more readable. I should have asked at the start but is there any docs that explain the MQL process? its quite complex and difficult to approach from fresh

2024-04-16 14:19 UTC, OButlerOcc commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/DataModelSqlExporterIntegrationSpec.groovy
> +        def dataModel = givenDataModel."baseline data for testing sql exports"(testUser, folder)
good change this, much more readable test pages

2024-04-16 14:19 UTC, OButlerOcc commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/testhelpers/MeqlTestGivens.groovy
> +class MeqlTestGivens {
I love seperate givens

2024-04-16 14:19 UTC, OButlerOcc commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/updater/SqlExportFieldUpdaterServiceSpec.groovy
> +        then: "it is added to the table"
slightly unexpected that the same col can be added twice, is this intended?

2024-04-16 14:19 UTC, OButlerOcc commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/updater/SqlExportRuleUpdaterService.groovy
> +    /*
remove commented code

2024-04-16 14:20 UTC, OButlerOcc approved these changes
clicked the wrong review button

2024-04-16 15:12 UTC, NigelPalmer commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/updater/SqlExportFieldUpdaterServiceSpec.groovy
> +        then: "it is added to the table"
The test is correct. If you look at the results only one column gets added. This is what is being tested. I have reworded the test descriptions to try and make it clearer.

2024-04-16 15:13 UTC, NigelPalmer commented on grails-app/services/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/sql/exporter/core/updater/SqlExportRuleUpdaterService.groovy
> +    /*
Removed

2024-04-16 15:18 UTC, NigelPalmer commented
Regarding documentation. this needs to be written but will do that later. The process is not as it should be yet. At the moment the SQL is generated by running an export in the MDM UI where as it needs to be generated automatically in the MDE when a Data Specification is submitted. There is also configuration that is required to set up the Query Builder, and this will need to be documented, although the Query Builder is being updated so that the error messages clearly describe what needs to be done.

2024-04-16 15:23 UTC, OButlerOcc commented on src/integration-test/groovy/uk/ac/ox/softeng/maurodatamapper/plugins/explorer/exporter/tests/updater/SqlExportFieldUpdaterServiceSpec.groovy
> +        then: "it is added to the table"
That makes sense, did think it was weird it worked as it stated

2024-04-16 15:24 UTC, OButlerOcc approved these changes
Changes are good, happy to tick, has not been end to end tested but andrew did it the review before and I checked the tests over.

2024-04-17 07:34 UTC, merged